"""Builds certs/iitb_ca_bundle.pem = certifi's CA bundle + the intermediate(s) a server fails to send.

Used by a source's optional `ca_bundle` config key (passed to requests as verify=<path>). Verification
stays on: the bundle only adds a CA certificate that the server should have sent itself.
Re-run after upgrading certifi (requirements.txt) so the bundle keeps the current roots.

Usage:  python scripts/build_ca_bundle.py
"""

from pathlib import Path

import certifi

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CERTS = PROJECT_ROOT / "certs"
INTERMEDIATES = [CERTS / "globalsign_rsa_ov_ssl_ca_2018.pem"]
BUNDLE = CERTS / "iitb_ca_bundle.pem"


def main() -> None:
    parts = [f"# Generated by scripts/build_ca_bundle.py from certifi {certifi.__version__} + "
             f"{', '.join(p.name for p in INTERMEDIATES)}. Do not edit by hand.\n",
             Path(certifi.where()).read_text(encoding="utf-8")]
    parts += [p.read_text(encoding="utf-8") for p in INTERMEDIATES]
    BUNDLE.write_text("\n".join(parts), encoding="utf-8", newline="\n")
    print(f"wrote {BUNDLE.relative_to(PROJECT_ROOT)} ({BUNDLE.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
